### DISCUSSION TITLE
Am I confused? Probably.

### DISCUSSION THREAD

**Discussion by darrenaddy** [theNewDynamic/huge#70] [Q&A]
I'm trying to figure out Hugo Module Mounts by looking at examples. The example provided in huge (config/_default/module.yml) looks like this:
```
mounts:
  - source: assets
    target: assets
  - source: _huge
    target: assets/_huge
imports:
  - path: github.com/theNewDynamic/huge
  ```
  So doesn't that tell me that you are taking a directory found at github.com/theNewDynamic/huge/_huge and mapping it to the Hugo project root > assets/_huge
??? Or am I already misunderstanding something? Because when I look at your repository, I find no directory named "_huge" anywhere.
