### ISSUE TITLE
Add "params" ability to styles

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/huge#32]
Just like we can easily pass `params` to the scripts which can be imported from the js code,

we could try and add the same for styles. Those could be inserted as css variables:

```yaml
styles:
-  path: main.scss
    params:
      env: huge/env/Get()
      darkMode: true
```

Which would generate something like:
```css
:root {
  --env: production
  --darkMode: true
}
```
