### ISSUE TITLE
SEO: Add FM key configuration

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/huge#39]
Currently HUGE/SEO assumes some keys should be used for SEO tags, like `image`, `images` etc.. We should allow user to set their own key for images and others through configuration

```yaml
#_huge/config/seo
mapping:
   featured: image
```
