### ISSUE TITLE
Scripts: Question our script tags crossorigin/defer defaults

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/huge#50]
Currently the user has no say in the default attributes we add to any `<script>` tag. 

```html
<script 
        src="https://..."
        type="text/javascript"
        crossorigin="anonymous" 
        defer="defer"
 </style>
```

1. We should investigate if these constitutes good defaults
2. We should allow user to overwrite these with configuration and add any custom attributes they see fit. Some libraries requires custom attributes. Iubenda and similar services as well etc...

**Comment by regisphilibert** [comment]
I think the current default should be kept allowing user to handle `crossorigin` and `defer` on the script configuration level if need to overwrite or not include.

I've also added a `custom attributes` API. So user can add anything like `data-something="test"` to the tag or overwrite the `type="text/javascript"` we something else as we had to do for iubenda GDPR.

```yaml
scripts:
- name: main
  path: js/main.js
  format: cjs
  fingerprint: always
  minify: production
  integrity: true
  defer: true
  crossorigin: use-credentials
  attributes:
    data-test: success
    async:
  params:
    list:
    - Sam
```

**Comment by regisphilibert** [comment]
@budparr after our enlightening discussion this morning I think we should have one config key for the loading strategy defaulting to defer. and which can take (for now) either `defer`, `async` or `none`

```
scripts:
- name: main
  path: js/main.js
  load: async
```
